drop table if exists
    "USER_GAME",
    "SCENE_ACTION",
    "SCENE_TEXT_CONTENT",
    "SCENE_CHARACTER_APPEARANCE",
    "PROJECT_INITIAL_SCENE",
    "SCENE",
    "CHARACTER_APPEARANCE",
    "RESOURCE",
    "CHARACTER",
    "USER_PROJECT_PERMISSION",
    "PROJECT",
    "USER";

drop type if exists
    "PERMISSION_TYPE";